### ISSUE TITLE
App not running in Macos

### ISSUE THREAD

**Issue by prabhuc94** [necodeIT/flutter_single_instance#1]

**Comment by otmi100** [comment]
I can confirm this. There is an exception when running _isFirstInstance_() for release-builds:

```
PathNotFoundException: PathNotFoundException: Cannot open file, path = '/Users/myuser/Library/Caches//Users/myuser/development/myapp/build/macos/Build/Products/Release/myapp.app/Contents/MacOS/myapp.pid' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
<asynchronous suspension>
#3      FlutterSingleInstanceBase._activateFirstInstance (package:flutter_single_instance/flutter_single_instance_base.dart:56)
<asynchronous suspension>
#4      FlutterSingleInstanceBase.isFirstInstance (package:flutter_single_instance/flutter_single_instance_base.dart:45)
```


[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale de-DE)
    • Flutter version 3.19.3 on channel stable at /Users/myuser/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (4 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

**Comment by mcquenji** [comment]
hmm interesting - will investigate

**Comment by mcquenji** [comment]
Could you please share your app entitlements? (macos/Runner/Release.entitlements)

**Comment by otmi100** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<false/>
</dict>
</plist>
```

**Comment by mcquenji** [comment]
hmm and its still not working? 

Sadly i dont have a mac - so i cant test :(

**Comment by mcquenji** [comment]
do you have the same entitlements for debug mode?

**Comment by mcquenji** [comment]
I've pushed a potential fix to the repo could you try if it resolves the issue with a dependency override?

```yaml
dependency_overrides:
  flutter_single_instance:
    git:
      url: https://github.com/necodeIT/flutter_single_instance.git
```

**Comment by AndreySosnovyy** [comment]
Hello!
Faced same issue and the fix didn't worked. As I can see the problem is not caused by absence of file in which you try to write, but by the wrong path to the file. Check the path from stack trace: /Users/myuser/Library/Caches//Users/myuser/...

**Comment by AndreySosnovyy** [comment]
I think that replacing `return parts.last;` to `return parts.last.split('/').last;` on 28th line in lib/src/macos.dart might be a quick solution.

**Comment by mcquenji** [comment]
could you make a pr? I don't have a mac to test potential fixes :(

**Comment by AndreySosnovyy** [comment]
[You are welcome! ](https://github.com/necodeIT/flutter_single_instance/pull/3)

By the way I have tested it, so it pretty much safe to merge.

> could you make a pr? I don't have a mac to test potential fixes :(
